class DataObject:
    def __init__(self):
        self.race = ""
        self.char_levels = []
        self.selected_skills = []
        self.skill_levels = {}

    def set_race(self, race):
        self.race = race

    def set_char_levels(self, char_levels):
        self.char_levels = char_levels

    def set_selected_skills(self, skills):
        self.selected_skills = skills

    def set_skill_levels(self, skill_levels):
        self.skill_levels = skill_levels

    def generate_selected_skill_levels(self):
        skill_info = self.get_race_skills_info()[self.race]
        self.skill_levels = {}
        for skill in self.selected_skills:
            self.skill_levels[skill] = skill_info[skill]

    @staticmethod
    def get_race_skills_info():
        return {
            "Breton": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Nord": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Imperial": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Redguard": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Altmer": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Bosmer": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Dunmer": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Orc": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Argonian": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            },
            "Khajiit": {
                "Illusion": 15,
                "Conjuration": 15,
                "Destruction": 15,
                "Restoration": 15,
                "Alteration": 15,
                "Enchanting": 15,
                "Smithing": 15,
                "Heavy Armor": 15,
                "Block": 15,
                "Two-handed": 15,
                "One-handed": 15,
                "Archery": 15,
                "Light Armor": 15,
                "Sneak": 15,
                "Lockpicking": 15,
                "Pickpocket": 15,
                "Speech": 15,
                "Alchemy": 15,
            }
        }
